[pytest]
; Pytest Configuration File

; addopts: This option allows you to specify additional command-line options that pytest should use when running tests.
;       -rA     : This option tells pytest to report all outcomes, including passing, skipped, and failed tests (-r)
;                    and show extra test summary info for passed tests (A).
;        -v     : This option increases verbosity, meaning pytest will output more detailed information about
;                    the tests being run.
;        --html : report.html: This option instructs pytest to generate an HTML report of the test results
;                    and save it to a file named report.html.

addopts = -rA -v --html=tests/test_report.html

; markers: This section allows you to define custom markers that can be used to selectively run tests or to apply
;           additional metadata to tests.

;           smoke: Mark tests as smoke tests, which are quick tests meant to check critical functionalities.
;           regression: Mark tests as regression tests, which verify that fixed bugs do not reoccur.
;           performance: Mark tests as performance tests, which assess the performance of specific functionalities.

markers =
    smoke: Mark tests as smoke tests
    regression: Mark tests as regression tests
    performance: Mark tests as performance tests
